# target: ~/.config/alacritty/alacritty.toml

# Must install catppuccin theme here:
# https://github.com/catppuccin/alacritty
import = ["/Users/hughm/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[cursor]
style = "Block"
vi_mode_style = "Beam"

[font]
size = 16

[font.glyph_offset]
x = 0
y = 1

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 3

[window.padding]
x = 16
y = 16
