# target: ~/Brewfile

tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "bat"
brew "coreutils"
brew "ctags-exuberant"
brew "exa"
brew "fzf"
brew "gpg2"
brew "htop"
brew "hub"
brew "jq"
brew "neovim"
brew "python3"
brew "ripgrep"
brew "starship"
brew "the_silver_searcher"
brew "tmate"
brew "tmux"
brew "tree"
brew "wget"

# ----------
# -- CASK --
# ----------
cask "1password"
cask "adobe-acrobat-reader"
cask "alfred"

# INSTALL FAILING
# cask "authy"
# cask "calibre"

cask "arq"
cask "charles"
cask "docker"
cask "dropbox"
brew "ffmpeg"
cask "firefox"
cask "font-firacode-nerd-font"
cask "google-chrome"
cask "graphql-playground"
cask "istat-menus"
cask "kitty"
cask "ngrok"
cask "now"
cask "postgres"
cask "postman"
cask "rectangle"
cask "skype"
cask "slack"
cask "spotify"
cask "typora"
cask "visual-studio-code"
cask "whatsapp"

# ============================
# ============================
# ============================

tap "heroku/brew"
brew "heroku"

# brew "certbot"
# brew "dep"
# brew "elixir"
# brew "exercism"
# brew "go"
# brew "kubectl"
# brew "pwgen"
# brew "scala"
# brew "ssh-copy-id"
# brew "vegeta"
# brew "watch"
# brew "yarn"

# cask "altair"
# cask "atom"
# cask "caskroom/versions/firefox-developer-edition"
# cask "cycling74-max"
# cask "discord"
# cask "gemini"
# cask "github"
# cask "google-backup-and-sync"
# cask "google-chrome-canary"
# cask "gpg-suite"
# cask "graphiql"
# cask "hyper"
# cask "imazing"
# cask "intel-power-gadget"
# cask "intellij-idea-ce"
# cask "iterm2"
# cask "kap"
# cask "kibana"
# cask "macdown"
# cask "notion"
# cask "postgres"
# cask "postico"
# cask "r-app"
# cask "rstudio"
# cask "sequel-pro"
# cask "sourcetree"
# cask "suspicious-package"
# cask "tableplus"
# cask "teamviewer"
# cask "virtualbox"
# cask "vlc"
